// Generated by pnpm new. Values are derived from the slug; do not edit by hand (docs/spec/publish-pipeline.md).
import { defineConfig } from 'vite';

export default defineConfig({
  root: import.meta.dirname,
  // Relative base so the build output can be moved (decision 0004). Do not write absolute paths in sketch code.
  base: './',
  build: {
    // Output straight into public/lab/<slug>/ (committed; served by Pages as-is. decision 0001).
    outDir: '../../public/lab/__SLUG__',
    emptyOutDir: true,
  },
});
