// Generated by pnpm new. A per-sketch copy: edit freely for this sketch only (docs/spec/publish-pipeline.md).
import { defineConfig } from 'vite';

// Property mangling renames every unquoted property (same policy as PaleGL for function-based code).
// Properties referenced by string (Tweakpane bindings, uniform names, JSON keys) must be quoted in the object
// literal: { 'speed': 1 }. Breakage only shows in the build output, so check the build output (docs/coding.md).
// Set to false if this sketch cannot follow that rule.
const mangleProperties = true;

export default defineConfig({
  root: import.meta.dirname,
  // Relative base so the build output can be moved (decision 0004). Do not write absolute paths in sketch code.
  base: './',
  build: {
    // Output straight into public/lab/<slug>/ (committed; served by Pages as-is. decision 0001).
    outDir: '../../public/lab/__SLUG__',
    emptyOutDir: true,
    target: 'esnext',
    // Sketches are a single chunk; the modulepreload polyfill is dead weight.
    modulePreload: { polyfill: false },
    minify: 'terser',
    terserOptions: {
      mangle: {
        toplevel: true,
        ...(mangleProperties ? { properties: { keep_quoted: true } } : {}),
      },
      compress: {
        passes: 1,
        arguments: true,
        booleans_as_integers: true,
        drop_console: true,
        drop_debugger: true,
        keep_fargs: false,
        module: true,
        pure_getters: true,
        unsafe: true,
        unsafe_math: true,
        unsafe_methods: true,
        unsafe_proto: true,
        unsafe_undefined: true,
      },
    },
  },
});
